<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Authors>Graham Downs</Authors>
    <Product>Mastodon Follower Times</Product>
    <Version>1.2.0</Version>
    <Copyright>Copyright © Graham Downs 2023</Copyright>
    <ApplicationIcon>MastodonFollowerTimes Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="MastodonFollowerTimes Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENCE" Link="LICENCE">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="111.4.1" />
  </ItemGroup>

</Project>
